### ISSUE TITLE
Multiple Blogs with same category names, the tag field will display the selected category multiple times

### ISSUE THREAD

**Issue by obj63mc** [silverstripe-labs/silverstripe-tagfield#171]
Affects SS 4.x, TagField Latest

First not sure if this is a Tag Field issue or a https://github.com/silverstripe/silverstripe-blog or more of a general SilverStripe issue with form scaffolding

To reproduce - 
1. Create a new SilverStripe Site
2. Install the Tagfield and Blog Module
3. Add two blogs
4. On Blog One add Categories 'Foo', 'Bar', 'Baz'
5. On Blog Two add Categories 'Foo' and 'Bar'
6. On Blog One - add a new post with the category 'Foo' - when searching the form will show only one option and when added to the field it is listed once.
7. Save the Page
8. On refresh the form field will display 'Foo' twice
9. Add Category 'Baz' to the post
10. Save Page will show - 'Foo, Foo, Baz'

I have some screenshots attached below. As with the testing in steps 9 and 10 if the category name isn't duplicated anywhere it shows singularly as it should. When looking in the database all is correct there, and when looking at the post counts and dumps of the posts categories the count is correct so not sure why the response back from the server is duplicated after the page is saved.

## Blog One with categories defined - 

example test is the Careers Category
![1BlogOne](https://user-images.githubusercontent.com/443120/93826959-f1485a00-fc2d-11ea-8e73-b3521536ee82.png)

## Blog Two with the same categories defined - 

you can see that category two shows proper count no posts in Careers
![2BlogTwo](https://user-images.githubusercontent.com/443120/93826958-f0afc380-fc2d-11ea-9a85-af6895ab07d1.png)

## Before Save adding the Category - Page ID 43, Category ID 7
![3BeforeSave](https://user-images.githubusercontent.com/443120/93826956-f0172d00-fc2d-11ea-8327-a40f8881d794.png)

## After Save - category is showing twice.
![4AfterSave](https://user-images.githubusercontent.com/443120/93826954-ef7e9680-fc2d-11ea-8704-5777a5921d6c.png)

## Database Table of Blog Categories - table name BlogCategory
![Database](https://user-images.githubusercontent.com/443120/93827341-b135a700-fc2e-11ea-9f7f-d21cbc6c24e0.png)

## Database table of saved relations - table name BlogPost_Categories

shows that data isn't duplicated it is singular per post as expected. only one row for Blog Post ID 43 and Category ID 7
![Screen Shot 2020-09-21 at 5 20 45 PM](https://user-images.githubusercontent.com/443120/93827406-cd394880-fc2e-11ea-8fec-fb9d4b949318.png)

**Comment by obj63mc** [comment]
So debugging this I believe the issue is around line 275 of src/TagField.php

        // Convert an array of values into a datalist of options
        if (is_array($values) && !empty($values)) {
            $values = DataList::create($dataClass)
                ->filter($this->getTitleField(), $values);
        }

Essentially even if I pass in the source list where it is filtered to just one specific blog, this is essentially looking at all items of the same class (BlogCategory) not a filtered version that was passed into the constructor and thus we get duplicates. Example below - 

    public function updateCMSFields(FieldList $fields)
    {
        $fields->removeByName('Tags');
        $fields->removeByName('Categories');
        $parent = $this->owner->Parent();
        $categories = $parent->Categories();
        $tags = $parent->Tags();

        $fields->addFieldsToTab(
            'Root.PostOptions',
            [
                TagField::create(
                    'Categories',
                    _t(__CLASS__ . '.Categories', 'Categories'),
                    $categories,
                    $this->owner->Categories()
                )
                    ->setCanCreate(false)
                    ->setShouldLazyLoad(false),
                TagField::create(
                    'Tags',
                    _t(__CLASS__ . '.Tags', 'Tags'),
                    $tags,
                    $this->owner->Tags()
                )
                    ->setCanCreate(true)
                    ->setShouldLazyLoad(false),
            ]
        );
    }

This should only be looking at that specific blogs categories and not all.  One way to fix this would be to only return unique items in your query when filtering by the title field.  The other is to check to see if the source is some subclass or a DataList first before trying to recreate one.

I could submit a PR for this but not sure which way you would want to go.  In the mean time I am just going to extend this class and utilize that internally.

**Comment by maxime-rainville** [comment]
Thanks for the detailed issue and diagnostic. Off the top of my head, the obvious fix would be to get the result from `$source` instead of creating a brand new DataList.

A PR would definitively be welcomed.

**Comment by michalkleiner** [comment]
PR merged to `2` and backported to `2.7`. Tagged `2.7.1`.

**Comment by michalkleiner** [comment]
Thanks @obj63mc for your contribution!
