### ISSUE TITLE
Selected tag is not shown when isMutliple is false

### ISSUE THREAD

**Issue by bumbus** [silverstripe-labs/silverstripe-tagfield#195]
I have no clue if I am using it wrong, but if `->setIsMultiple(false)` is set a selected tag title is not displayed.
But the record in the many_many junction table is created and the `X` also shows that some relation is present.

![Screenshot](https://user-images.githubusercontent.com/1391103/137150819-430b4558-420b-479d-8a14-ce62fa72da23.png)

### PRs
- https://github.com/silverstripe/silverstripe-tagfield/pull/201

**Comment by micschk** [comment]
I can confirm this issue, `->setIsMultiple(false)` results in the current value not being displayed.
I suspect this has something to do with the check around line 13 in TagField.js.:
```
    if (!this.isControlled()) {
      this.state = {
        value: props.value,
      };
    }
```

Would have been happy to attempt a fix but as its react and I need to install like an extra operating system before I can  attempt anything, I'm leaving this to the pros. [#6689](https://github.com/silverstripe/silverstripe-framework/issues/6689)

**Comment by emteknetnz** [comment]
Linked PR has been merged
