### ISSUE TITLE
TagField triggers edit form change state when there are no changes

### ISSUE THREAD

**Issue by obj63mc** [silverstripe-labs/silverstripe-tagfield#247]
Looks like with SS5 release, related to the old issue #125. Currently on a site using a tag field, whenever a cms page is loaded - it thinks there are changes that need to be saved.

Example on a pages getCMSFields function - 

```php
$this->beforeUpdateCMSFields(function ($fields) {
    $fields->addFieldToTab('Root.Main', TagField::create(
        'ProductPages',
        'Products',
        ProductPage::get(),
        $this->ProductPages()
    )->setCanCreate(false)->setShouldLazyLoad(true), 'Content');
});
```

When I load any page in the CMS that currently has a value set - the Save/Publish buttons are lit up as green post page load causing the form to think the edit state is changed, thus when clicking off it asks if you want to leave due to unsaved changes.  If I comment out this field all works as normal.

## PR
- https://github.com/silverstripe/silverstripe-tagfield/pull/251

**Comment by GuySartorelli** [comment]
PR merged and tagged as [3.0.1](https://github.com/silverstripe/silverstripe-tagfield/releases/tag/3.0.1)
