### ISSUE TITLE
No Tags available if not lazy loading

### ISSUE THREAD

**Issue by asecondwill** [silverstripe-labs/silverstripe-tagfield#25]
When not Lazy Loading, for pages with tags, the list displays all the avilable tags.  For new pages with no tags the list is empty.  Turning on lazy loading fixes this. 

````
    $field = new TagField(
      'RelationTags', 'Nursing, Corporate etc', Tag::get(), $this->RelationTags()
    );
//    $field->setShouldLazyLoad(true); // uncomment to workaround
    $field->setCanCreate(true);      // new tag DataObjects can be created
````

**Comment by mlewis-everley** [comment]
I am also having this issue, I have to manually enable lazy loading to fix it.
