### ISSUE TITLE
TODO: Assess whether we require lazy loading limits for the StringTagField

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe-labs/silverstripe-tagfield#263]
## Description
We need to evaluate the necessity of lazy loading limits for the StringTagField. If unnecessary, we should consider removing this restriction.
See https://github.com/silverstripe/silverstripe-tagfield/blob/a7023742a8fe3860caa53f3dc49285b6bb293b4e/src/StringTagField.php#L369-L370

**Comment by GuySartorelli** [comment]
Gonna close this as a "won't do" - the limit is configurable if it's causing problems for anyone.
It could also prevent us from loading a buttload of elements to memory, except that `getOptions()` isn't implemented in a way that allows that optimisation. That would be a separate card though.
