### ISSUE TITLE
Merge-up from 2 to 3.0

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe-labs/silverstripe-tagfield#265]
There's a mildly tricky merge up for 3.0 to 2

https://github.com/silverstripe/silverstripe-tagfield/compare/3.0...2 - doesn't quite capture it all, there is also a merge-conflict for the `<EmotionCssCacheProvider>` block as well

I don't want to merge this one up right now due to the 5.1 stable release being done later today

**Comment by GuySartorelli** [comment]
Merge up successful
