### ISSUE TITLE
Example in readme for StringTagField shows deprecation warning

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe-labs/silverstripe-tagfield#268]
The example in the readme

```php
$field = StringTagField::create(
    'Tags',
    'Tags',
    ['one', 'two'],
    explode(',', $this->Tags)
);
```

Will show the following warning if copy pasted:

`[Deprecated] explode(): Passing null to parameter #2 ($string) of type string is deprecated`

This is because $this->Tags starts off as `null`

## PR
- https://github.com/silverstripe/silverstripe-tagfield/pull/269

**Comment by GuySartorelli** [comment]
PR merged
