### ISSUE TITLE
SS5 z-index of dropdown behind TinyMCE

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe-labs/silverstripe-tagfield#270]
**SS5 Screenshot**

![image](https://github.com/silverstripe/silverstripe-tagfield/assets/178039/b45bb8dc-380a-4df6-873a-dfb1f6429e9d)

**SS4 Screenshot**

![image](https://github.com/silverstripe/silverstripe-tagfield/assets/178039/5c44cf60-69ab-46e6-bd6d-d7ae3310f858)

Increasing the z-index of the dropdown seems to fix the issue as `.tox .tox-editor-header` has a z-index of 1 also.

## PR
- https://github.com/silverstripe/silverstripe-tagfield/pull/271
- https://github.com/silverstripe/silverstripe-tagfield/pull/272

**Comment by michalkleiner** [comment]
Thanks for the report @christopherdarling, do you wanna try to create a PR with a fix?

**Comment by christopherdarling** [comment]
@michalkleiner looks like https://github.com/JedWatson/react-select/blob/06e34882638d1526b9f5a1238bb567a3e9460ce5/packages/react-select/src/components/Menu.tsx#L292 needs changing, I have had a look through the docs but can't see a way of updating this. 

There is an open ticket (https://github.com/JedWatson/react-select/issues/5329) and a few closed ones on this subject but doesn't seem to be a solution so might be a style we need to override through the tagfield styles. I'll send a PR later/soon.

**Comment by christopherdarling** [comment]
lint wasn't working on my local set up so you may want to re-build this but this seems to work; https://github.com/silverstripe/silverstripe-tagfield/pull/271

**Comment by christopherdarling** [comment]
new PR @ https://github.com/silverstripe/silverstripe-tagfield/pull/272 @GuySartorelli (with a better description too 😉 )

**Comment by GuySartorelli** [comment]
Thanks for reporting and fixing that! The patch will be automatically tagged by GitHub actions
