### ISSUE TITLE
How do you disable the create tags option?

### ISSUE THREAD

**Issue by mediabeastnz** [silverstripe-labs/silverstripe-tagfield#47]
Current if you type in a option that doesn't exist and hit enter a tag will be created inside the textfield.
I see there is an option in the TagField.js:
```javascript
var options = {
	'tags': true,
	'tokenSeparators': [',']
};
```

How do i make this false without editing the module itself?

**Comment by assertchris** [comment]
`$field->canCreate(false)`. Then they are ignored upon submission. Currently there is no way to stop them being added to the field. Perhaps a good thing to add...

**Comment by mediabeastnz** [comment]
I'll see what I can do ;)
