### ISSUE TITLE
Improve the "can create" API

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe-labs/silverstripe-tagfield#80]
Hi guys,

Nice module!

I went to add a permission for "create new tags" today and grant it for admins but not for another role.

I see that the follow behaviours exist:

* Regardless of what `TagField::getCanCreate` returns, a new tag is always shown in the select when entered
* If the permission is to deny, the user can still select the new tag, and it is still added to the select area
* On saving the Page (or whatever the TagField is in) the new tag is discarded

It'd be great if we could not show new tags if you don't have permission to create them!

Cheers,
Robbie

**Comment by tractorcow** [comment]
We probably need to put the getCanCreate into a property on the field, and have [TagField.js](https://github.com/silverstripe-labs/silverstripe-tagfield/blob/master/js/TagField.js) pick this up.

According to http://stackoverflow.com/questions/30471338/how-to-disable-creating-new-tags-with-select2-v4-0 you can probably set 	'tags: false' if canCreate is false.

Want to test and maybe PR this @robbieaverill ?

**Comment by robbieaverill** [comment]
Yeah why not, give me a couple f days to find some time :-)
>
>

-- 
*Robbie Averill*
LA PETITE MANOUCHE - NZ Gypsy Jazz Guitar Duo
Phone: +64 27 321 4758
contact@lapetitemanouche.com
www.lapetitemanouche.com

**Comment by robbieaverill** [comment]
All yours @tractorcow - works nicely for me. Thanks!
